### ISSUE TITLE
test load on the four dynos

### ISSUE THREAD

**Issue by misterinterrupt** [misterinterrupt/polyenvironments#9]
use apache bench to curl the crap out of the servers at the sound download urls

**Comment by misterinterrupt** [comment]
results from a free heroku thing
![screen shot 2016-08-11 at 7 52 29 pm](https://cloud.githubusercontent.com/assets/286920/17611555/4f6ad97c-5ffd-11e6-81bd-20d67ecc56f2.JPG)

**Comment by misterinterrupt** [comment]
@ryanstevens does this show much to you? other than heroku is expensive

**Comment by ryanstevens** [comment]
looks legit, lots of requests, no errors.  Does apache bench summary match?  Now what happens when you do the same AB test but with one more dyno

I would also redo the test but double the concurrency for fun.

**Comment by misterinterrupt** [comment]
could I try removing a dyno ? this is with 4.
